create table if not exists public.liankan_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 16),
  score integer not null check (score >= 0),
  moves integer not null default 0,
  seconds_left integer not null default 0,
  reshuffles integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.liankan_scores enable row level security;

drop policy if exists "Anyone can read scores" on public.liankan_scores;
create policy "Anyone can read scores"
  on public.liankan_scores
  for select
  to anon
  using (true);

drop policy if exists "Anyone can insert scores" on public.liankan_scores;
create policy "Anyone can insert scores"
  on public.liankan_scores
  for insert
  to anon
  with check (score >= 0 and char_length(player_name) between 1 and 16);

create index if not exists liankan_scores_rank_idx
  on public.liankan_scores (score desc, created_at asc);
